shfmt

diff --git a/,snapraid_diff_n_sync b/,snapraid_diff_n_sync
--- a/,snapraid_diff_n_sync
+++ b/,snapraid_diff_n_sync
@@ -51,68 +51,67 @@ SCRUB_FREQUENCY_IN_DAYS=7
 
 mkdir -p /root/.snapraid/
 
-if [[ -f /root/.snapraid/snapraid_scrub_counter ]]
-then
-  COUNTER=$(cat /root/.snapraid/snapraid_scrub_counter)
+if [[ -f /root/.snapraid/snapraid_scrub_counter ]]; then
+    COUNTER=$(cat /root/.snapraid/snapraid_scrub_counter)
 else
-  echo "1" > /root/.snapraid/snapraid_scrub_counter
-  COUNTER=1
+    echo "1" >/root/.snapraid/snapraid_scrub_counter
+    COUNTER=1
 fi
-COUNTER=$(($COUNTER+0))
+COUNTER=$(($COUNTER + 0))
 ### End Scrub Section ###
 
 ## INTERNAL TEMP VARS ##
 TMP_OUTPUT="/tmp/snapraid.out"
 # redirect all stdout to log file (leave stderr alone though)
-exec >> $LOG_FILE
+exec >>$LOG_FILE
 # timestamp the job
 echo "[$(date)] SnapRAID Job started."
-echo "SnapRAID DIFF Job started on $(date)" > $TMP_OUTPUT
-echo "----------------------------------------" >> $TMP_OUTPUT
+echo "SnapRAID DIFF Job started on $(date)" >$TMP_OUTPUT
+echo "----------------------------------------" >>$TMP_OUTPUT
 #TODO - mount and unmount parity disk on demand!
 #sanity check first to make sure we can access the content and parity files
 if [ ! -e $CONTENT_FILE ]; then
-  echo "[$(date)] ERROR - Content file ($CONTENT_FILE) not found!"
-  echo "ERROR - Content file ($CONTENT_FILE) not found!" >> $TMP_OUTPUT
-  exit 1;
+    echo "[$(date)] ERROR - Content file ($CONTENT_FILE) not found!"
+    echo "ERROR - Content file ($CONTENT_FILE) not found!" >>$TMP_OUTPUT
+    exit 1
 fi
 if [ ! -e "$PARITY_FILE" ]; then
-  echo "[$(date)] ERROR - Parity file ($PARITY_FILE) not found!"
-  echo "ERROR - Parity file ($PARITY_FILE) not found!" >> $TMP_OUTPUT
-  exit 1;
+    echo "[$(date)] ERROR - Parity file ($PARITY_FILE) not found!"
+    echo "ERROR - Parity file ($PARITY_FILE) not found!" >>$TMP_OUTPUT
+    exit 1
 fi
 # run the snapraid DIFF command
 echo "[$(date)] Running DIFF Command."
-$SNAPRAID_BIN diff >> $TMP_OUTPUT
+$SNAPRAID_BIN diff >>$TMP_OUTPUT
 # wait for the above cmd to finish
 wait
-echo "----------------------------------------" >> $TMP_OUTPUT
-echo "SnapRAID DIFF Job finished on $(date)" >> $TMP_OUTPUT
+echo "----------------------------------------" >>$TMP_OUTPUT
+echo "SnapRAID DIFF Job finished on $(date)" >>$TMP_OUTPUT
 DEL_COUNT=$(grep -w '^ \{1,\}[0-9]* removed$' $TMP_OUTPUT | sed 's/^ *//g' | cut -d ' ' -f1)
 ADD_COUNT=$(grep -w '^ \{1,\}[0-9]* added$' $TMP_OUTPUT | sed 's/^ *//g' | cut -d ' ' -f1)
 MOVE_COUNT=$(grep -w '^ \{1,\}[0-9]* moved$' $TMP_OUTPUT | sed 's/^ *//g' | cut -d ' ' -f1)
 COPY_COUNT=$(grep -w '^ \{1,\}[0-9]* copied$' $TMP_OUTPUT | sed 's/^ *//g' | cut -d ' ' -f1)
 UPDATE_COUNT=$(grep -w '^ \{1,\}[0-9]* updated$' $TMP_OUTPUT | sed 's/^ *//g' | cut -d ' ' -f1)
-echo "SUMMARY of changes - Added [$ADD_COUNT] - Deleted [$DEL_COUNT] - Moved [$MOVE_COUNT] - Copied [$COPY_COUNT] - Updated [$UPDATE_COUNT]" >> $TMP_OUTPUT
+echo "SUMMARY of changes - Added [$ADD_COUNT] - Deleted [$DEL_COUNT] - Moved [$MOVE_COUNT] - Copied [$COPY_COUNT] - Updated [$UPDATE_COUNT]" >>$TMP_OUTPUT
 # check if files have changed
 if [ "$DEL_COUNT" -gt 0 ] || [ "$ADD_COUNT" -gt 0 ] || [ "$MOVE_COUNT" -gt 0 ] || [ "$UPDATE_COUNT" -gt 0 ]; then
     # YES, check if number of deleted files exceed DEL_THRESHOLD
     if [ "$DEL_COUNT" -gt $DEL_THRESHOLD ]; then
         # YES, lets inform user and not proceed with the sync just in case
-        echo "Number of deleted files ($DEL_COUNT) exceeded threshold ($DEL_THRESHOLD). NOT proceeding with sync job. Please run sync manually if this is not an error condition." >> $TMP_OUTPUT
-    /usr/bin/mutt -s "$EMAIL_SUBJECT_PREFIX WARNING - Number of deleted files ($DEL_COUNT) exceeded threshold ($DEL_THRESHOLD)" -a $TMP_OUTPUT -- "$EMAIL_ADDRESS"
-    echo "WARNING - Deleted files ($DEL_COUNT) exceeded threshold ($DEL_THRESHOLD). Check $TMP_OUTPUT for details. NOT proceeding with sync job."
+        echo "Number of deleted files ($DEL_COUNT) exceeded threshold ($DEL_THRESHOLD). NOT proceeding with sync job. Please run sync manually if this is not an error condition." >>$TMP_OUTPUT
+        /usr/bin/mutt -s "$EMAIL_SUBJECT_PREFIX WARNING - Number of deleted files ($DEL_COUNT) exceeded threshold ($DEL_THRESHOLD)" -a $TMP_OUTPUT -- "$EMAIL_ADDRESS"
+        echo "WARNING - Deleted files ($DEL_COUNT) exceeded threshold ($DEL_THRESHOLD). Check $TMP_OUTPUT for details. NOT proceeding with sync job."
     else
         # NO, delete threshold not reached, lets run the sync job
-        echo "Deleted files ($DEL_COUNT) did not exceed threshold ($DEL_THRESHOLD), proceeding with sync job." >> $TMP_OUTPUT
+        echo "Deleted files ($DEL_COUNT) did not exceed threshold ($DEL_THRESHOLD), proceeding with sync job." >>$TMP_OUTPUT
         echo "[$(date)] Changes detected [A-$ADD_COUNT,D-$DEL_COUNT,M-$MOVE_COUNT,U-$UPDATE_COUNT] and deleted files ($DEL_COUNT) is below threshold ($DEL_THRESHOLD). Running SYNC Command."
-        echo "SnapRAID SYNC Job started on $(date)" >> $TMP_OUTPUT
-        echo "----------------------------------------" >> $TMP_OUTPUT
-        $SNAPRAID_BIN sync >> $TMP_OUTPUT
+        echo "SnapRAID SYNC Job started on $(date)" >>$TMP_OUTPUT
+        echo "----------------------------------------" >>$TMP_OUTPUT
+        $SNAPRAID_BIN sync >>$TMP_OUTPUT
         #wait for the job to finish
         wait
-        echo "----------------------------------------" >> $TMP_OUTPUT
-        echo "SnapRAID SYNC Job finished on $(date)" >> $TMP_OUTPUT
+        echo "----------------------------------------" >>$TMP_OUTPUT
+        echo "SnapRAID SYNC Job finished on $(date)" >>$TMP_OUTPUT
 
         # cleanup email body
         grep -E -v "^[[:digit:]]+" $TMP_OUTPUT | /usr/bin/mutt -s "$EMAIL_SUBJECT_PREFIX Sync Job COMPLETED" -a $TMP_OUTPUT -- "$EMAIL_ADDRESS"
@@ -120,34 +119,34 @@ if [ "$DEL_COUNT" -gt 0 ] || [ "$ADD_COUNT" -gt 0 ] || [ "$MOVE_COUNT" -gt 0 ] |
         # Run Scrub
         if [ $RUN_SCRUB = "true" ]; then
             if [ $COUNTER -lt $SCRUB_FREQUENCY_IN_DAYS ]; then
-               echo "[$(date)] Cycle count not met.  No scrub was run."
-               COUNTER=$(($COUNTER + 1))
-               echo "$COUNTER" > /root/.snapraid/snapraid_scrub_counter
+                echo "[$(date)] Cycle count not met.  No scrub was run."
+                COUNTER=$(($COUNTER + 1))
+                echo "$COUNTER" >/root/.snapraid/snapraid_scrub_counter
             else
-               echo "Running SnapRAID full scrub.  This will take a while" > $TMP_OUTPUT
+                echo "Running SnapRAID full scrub.  This will take a while" >$TMP_OUTPUT
 
-               echo "SnapRAID SCRUB started on $(date)" >> $TMP_OUTPUT
-               echo "----------------------------------------" >> $TMP_OUTPUT
+                echo "SnapRAID SCRUB started on $(date)" >>$TMP_OUTPUT
+                echo "----------------------------------------" >>$TMP_OUTPUT
 
-               $SNAPRAID_BIN scrub -p 100 -o 0 >> $TMP_OUTPUT
+                $SNAPRAID_BIN scrub -p 100 -o 0 >>$TMP_OUTPUT
 
-               #wait for the job to finish
-               wait
-               echo "----------------------------------------" >> $TMP_OUTPUT
-               echo "SnapRAID SCRUB finished on $(date)" >> $TMP_OUTPUT
+                #wait for the job to finish
+                wait
+                echo "----------------------------------------" >>$TMP_OUTPUT
+                echo "SnapRAID SCRUB finished on $(date)" >>$TMP_OUTPUT
 
-               # Reset counter
-               echo "1" > /root/.snapraid/snapraid_scrub_counter
+                # Reset counter
+                echo "1" >/root/.snapraid/snapraid_scrub_counter
 
-               # cleanup email body
-               grep -E -v "^[[:digit:]]+" $TMP_OUTPUT | /usr/bin/mutt -s "$EMAIL_SUBJECT_PREFIX Full Scrub COMPLETED" -a $TMP_OUTPUT -- "$EMAIL_ADDRESS"
+                # cleanup email body
+                grep -E -v "^[[:digit:]]+" $TMP_OUTPUT | /usr/bin/mutt -s "$EMAIL_SUBJECT_PREFIX Full Scrub COMPLETED" -a $TMP_OUTPUT -- "$EMAIL_ADDRESS"
 
-               $SNAPRAID_BIN status > $TMP_OUTPUT
-               /usr/bin/mutt -s "$EMAIL_SUBJECT_PREFIX Status" "$EMAIL_ADDRESS" < $TMP_OUTPUT
+                $SNAPRAID_BIN status >$TMP_OUTPUT
+                /usr/bin/mutt -s "$EMAIL_SUBJECT_PREFIX Status" "$EMAIL_ADDRESS" <$TMP_OUTPUT
 
             fi
         else
-               echo "Array scrubbing is not enabled.  If you would like to enable it, please set the RUN_SCRUB option to true."
+            echo "Array scrubbing is not enabled.  If you would like to enable it, please set the RUN_SCRUB option to true."
         fi
     fi
 else
@@ -155,4 +154,4 @@ else
     echo "[$(date)] No change detected. Nothing to do"
 fi
 echo "[$(date)] Job ended."
-exit 0;
+exit 0
